services:
  - type: web
    name: backend
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    plan: free
    port: 8000
    regions:
      - oregon
